services:
  - type: web
    name: irunsvan-reseller-site
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    branch: main
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
