const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const appSource = readFileSync(join(__dirname, "..", "src", "app.js"), "utf8");
const styleSource = readFileSync(join(__dirname, "..", "src", "styles.css"), "utf8");
const indexSource = readFileSync(join(__dirname, "..", "index.html"), "utf8");
const staticServerSource = readFileSync(join(__dirname, "..", "scripts", "serve-static.js"), "utf8");
const staticBuildSource = readFileSync(join(__dirname, "..", "scripts", "build-static.js"), "utf8");
const authSource = readFileSync(join(__dirname, "..", "src", "auth.js"), "utf8");
const supabaseClientSource = readFileSync(join(__dirname, "..", "src", "supabase-client.js"), "utf8");
const createTestAdminsSource = readFileSync(join(__dirname, "..", "scripts", "create-test-admins.js"), "utf8");
const emailDispatcherSource = readFileSync(join(__dirname, "..", "supabase", "functions", "_shared", "email-dispatcher.ts"), "utf8");
const resellerProductCardSource = appSource.match(/function resellerProductCard\([\s\S]*?\n}\n\nfunction resellerColourGroups/)?.[0] || "";
const productFlyerPageSource = appSource.match(/function productFlyersPage\([\s\S]*?\n}\n\nfunction productFlyerDetailPage/)?.[0] || "";
function sourceBetween(start, end) {
  const startIndex = appSource.indexOf(start);
  if (startIndex < 0) return "";
  const endIndex = appSource.indexOf(end, startIndex);
  return endIndex < 0 ? appSource.slice(startIndex) : appSource.slice(startIndex, endIndex);
}
const selectorGroupSource = sourceBetween("function selectorGroup(", "function filterGroup");
const pagerSource = sourceBetween("function pager(", "function catalogPager");

assert.equal(appSource.includes("<button>View all</button>"), false, "View all buttons must navigate or trigger an action.");
assert.equal(indexSource.includes('name="irunsvan-build-commit" content="__BUILD_COMMIT__"'), true, "The static build must expose its deployed Git commit.");
assert.equal(staticBuildSource.includes("process.env.COMMIT_REF"), true, "Netlify's commit reference must populate the production build marker.");
assert.equal(appSource.includes('<button class="button mini">Approve</button>'), false, "Approve buttons must use real approval actions.");
assert.equal(appSource.includes('<button class="button mini secondary">Reject</button>'), false, "Reject buttons must use real rejection actions.");
assert.equal(appSource.includes("function applicationActionFeedback()"), true, "Application approvals must show a visible success or failure result.");
assert.equal(appSource.includes("if (!result?.ok) throw new Error"), true, "Application approval must not silently accept an unconfirmed email response.");
assert.equal(appSource.includes('<button class="button secondary">View Template</button>'), false, "Email template buttons must open a real preview.");
assert.equal(appSource.includes("Saved only in this browser"), false, "Product saves must not fall back to browser-only data.");
assert.equal(appSource.includes("Product draft is visible locally"), false, "Product saves must fail loudly instead of creating local-only products.");
assert.equal(appSource.includes('<p class="detail-price">${money(product.base_price)}</p>'), false, "Public product detail must not show prices.");
assert.equal(appSource.includes("<strong>${money(product.base_price)}</strong>"), false, "Public product cards must not show prices.");
assert.equal(appSource.includes("Price: Low to High"), false, "Public catalogue must not offer price sorting.");
assert.equal(appSource.includes("Price Range"), false, "Public catalogue must not expose price filtering.");
assert.equal(appSource.includes("Public browsing shows product information and pricing"), false, "Public catalogue copy must not promise public pricing.");
assert.equal(appSource.includes('${inputField("Product Type", "product_type", "shoe")}'), true, "Admin product form must let the admin choose product type.");
assert.equal(appSource.includes("product_type: data.get(\"product_type\")"), true, "Product saves must use the admin-entered product type.");
assert.equal(appSource.includes("LOGIN_BYPASS"), false, "Frontend must not include login bypass logic.");
assert.equal(appSource.includes("buildLocalAdminAuthState"), false, "Frontend must not build fake admin auth state.");
assert.equal(appSource.includes("resolveBypassAuthState"), false, "Frontend must not restore bypass auth state.");
assert.equal(appSource.includes("dev-admin-login"), false, "Login page must not expose a dev admin login action.");
assert.equal(appSource.includes("/__dev/prelogin"), false, "Login page must not link to prelogin endpoints.");
assert.equal(appSource.includes("Preview admin shell"), false, "Login page must not expose admin preview shell access.");
assert.equal(appSource.includes('data-action="google-login"'), true, "Login page must expose Google OAuth login.");
assert.equal(appSource.includes("function handleGoogleLogin()"), true, "Google OAuth login must have a dedicated handler.");
assert.equal(appSource.includes("SupabaseClient.signInWithOAuth({"), true, "Google login must use Supabase OAuth instead of bypass logic.");
assert.equal(appSource.includes("signup: signupPage"), true, "Normal email account creation must have a dedicated signup route.");
assert.equal(appSource.includes("function signupPage()"), true, "Signup page must render a first-class email account creation form.");
assert.equal(appSource.includes('["Create account", "signup"]'), true, "Login must expose normal email account creation.");
assert.equal(appSource.includes("function publicNavItems("), true, "Public navigation must be generated from one consolidated item list.");
assert.equal(appSource.includes('["Access", "signup", ["signup"]]'), false, "Public top navigation must not expose duplicate account access links.");
assert.equal(appSource.includes('["Join", "apply", ["apply"]]'), false, "Public top navigation must not duplicate Join Network.");
assert.equal(appSource.includes("const publicItems = publicNavItems();"), true, "Top navigation must use the consolidated public nav list.");
assert.equal(appSource.includes('inputField("Confirm Password", "password_confirm"'), true, "Signup must require password confirmation.");
assert.equal(appSource.includes("state.signupConfirmationEmail = email;"), true, "Signup must handle email confirmation before application submission.");
assert.equal(appSource.includes('["Back to public site", "store"]'), true, "Admin login should point back to the public site instead of reseller application.");
assert.equal(appSource.includes('inputField("Username", "username", "RAMOCHA")'), true, "Admin login must use a username field instead of exposing an email requirement.");
assert.equal(appSource.includes("SupabaseClient.adminLoginEmail(username)"), true, "Admin username login must resolve through the tested Supabase identifier mapping.");
assert.equal(appSource.includes("SupabaseClient.consumeOAuthSessionFromUrl()"), true, "Startup must consume Supabase OAuth callback sessions.");
assert.equal(appSource.includes("const hasOAuthError = Boolean(oauthResult.error || oauthError);"), true, "OAuth error handling must be explicit during startup.");
assert.equal(appSource.includes('window.history.replaceState({}, "", `${window.location.pathname}${MobileNavigation.buildRouteUrl(state.route)}`);'), true, "OAuth errors must clean the visible URL before routing.");
assert.equal(appSource.includes("if (!hasOAuthError) {"), true, "OAuth errors must not fall through to the hash-based route restore.");
assert.equal(supabaseClientSource.includes("function buildOAuthUrl("), true, "Supabase client must build provider OAuth authorize URLs.");
assert.equal(supabaseClientSource.includes("function authErrorMessage("), true, "Supabase client must normalize auth provider and credential errors.");
assert.equal(supabaseClientSource.includes("function oauthResultFromSearch("), true, "Supabase client must inspect OAuth callback query parameters.");
assert.equal(supabaseClientSource.includes("function oauthSessionFromHash("), true, "Supabase client must parse OAuth callback hash sessions.");
assert.equal(supabaseClientSource.includes("error_code"), true, "OAuth error_code must be treated as a callback parameter.");
assert.equal(appSource.includes('searchParams.delete("error_code")'), true, "OAuth redirect URLs must not keep stale error_code query parameters.");
assert.equal(authSource.includes("buildDevAdminAuthState"), false, "Auth module must not export fake dev admin state.");
assert.equal(appSource.includes("const WebsiteContent = window.IrunsvanWebsiteContent;"), true, "App must load website content helpers.");
assert.equal(appSource.includes("homepageFlyers:"), true, "App state must track homepage flyers.");
assert.equal(appSource.includes("blogPosts:"), true, "App state must track blog posts.");
assert.equal(appSource.includes("selectedStorySlug:"), true, "App state must track selected story slug.");
assert.equal(appSource.includes("publicProductFlyers:"), true, "App state must track public product flyers separately from reseller products.");
assert.equal(appSource.includes("selectedProductFlyerSlug:"), true, "App state must track the selected public product flyer slug.");
assert.equal(appSource.includes('fetchOptionalSupabase("homepage_flyers"'), true, "Public bootstrap must fetch published homepage flyers.");
assert.equal(appSource.includes('fetchOptionalSupabase("blog_posts"'), true, "Public bootstrap must fetch published blog posts.");
assert.equal(appSource.includes('fetchOptionalSupabaseResult("public_product_flyers"'), true, "Public bootstrap must fetch published public product flyers.");
assert.equal(appSource.includes('fetchAuthedSupabase("homepage_flyers"'), true, "Admin bootstrap must fetch all homepage flyers.");
assert.equal(appSource.includes('fetchAuthedSupabase("blog_posts"'), true, "Admin bootstrap must fetch all blog posts.");
assert.equal(appSource.includes('fetchAuthedSupabase("public_product_flyers"'), true, "Admin bootstrap must fetch all public product flyers.");
assert.equal(appSource.includes('"story"'), true, "Story route must be registered.");
assert.equal(appSource.includes('"product-flyers"'), true, "Public product flyer listing route must be registered.");
assert.equal(appSource.includes('"product-flyer"'), true, "Public product flyer detail route must be registered.");
assert.equal(appSource.includes("loadCatalog();\ninitAuth();"), false, "Startup must not fire catalog and auth without explicit orchestration.");
assert.equal(appSource.includes("await loadCatalog();\n  await initAuth();"), false, "OAuth callback routing must not wait for the public catalog before auth restore.");
assert.equal(appSource.includes("const catalogLoad = loadCatalog();"), true, "Startup must begin catalog loading without blocking auth restore.");
assert.equal(appSource.includes("await initAuth({ loadProtected: false });"), true, "OAuth callback routing must restore auth before protected data loading.");
assert.equal(appSource.includes("state.authBootstrapPending = false;"), true, "Auth bootstrap screen must be cleared before background protected data loading.");
assert.equal(appSource.includes("loadProtectedData().catch"), true, "Protected data should load in the background after sign-in routing.");
assert.equal(appSource.includes('const desktopItems = portalMode === "public" ? publicItems : portalMode === "reseller" ? resellerNavItems : [];'), true, "Admin workspace should not duplicate the full top navigation.");
assert.equal(appSource.includes("const resellerNavItems ="), true, "Reseller workspace should use a smaller dedicated top navigation.");
assert.equal(appSource.includes('if (state.auth.isPending) {'), true, "Pending users need a distinct workspace menu.");
assert.equal(appSource.includes('const url = `${window.location.pathname}${MobileNavigation.buildRouteUrl(nextRoute, historyState)}`;'), true, "Route writes must clear stale search params when changing pages.");
assert.equal(appSource.includes("const cleanUrl = `${window.location.pathname}${MobileNavigation.buildRouteUrl(nextRoute, {"), true, "Route sync must clear stale search params when restoring hashes.");
assert.equal(appSource.includes("orderId: state.selectedOrderId,"), true, "Route sync must preserve order IDs in the URL.");
assert.equal(appSource.includes('"order"'), true, "Order route must be registered.");
assert.equal(appSource.includes("selectedOrderId:"), true, "App state must track the selected order ID.");
assert.equal(appSource.includes('orderId: button.getAttribute("data-order-id")'), true, "Route buttons must pass order IDs.");
assert.equal(appSource.includes("const restored = await SupabaseClient.restoreAuthState({ url: SUPABASE_URL, key: SUPABASE_KEY });"), true, "Startup must restore real Supabase sessions before protected data loading.");
assert.equal(supabaseClientSource.includes("if (!session?.access_token) return { session: null, user: null, profile: null };"), true, "Auth restore must not create protected access without a real Supabase session.");
assert.equal(appSource.includes("async function requireAuthedSession()"), true, "Protected mutations must be able to refresh Supabase sessions before using stored tokens.");
assert.equal(appSource.includes("await SupabaseClient.getValidSession({ url: SUPABASE_URL, key: SUPABASE_KEY })"), true, "Protected Supabase calls must refresh expired sessions before authenticated REST requests.");
assert.equal(appSource.includes("Sign in as a test reseller"), false, "Reseller portal must not mention test-session login paths.");
assert.equal(appSource.includes("function requireAuthedSession()"), true, "Protected mutations must require a real Supabase session.");
assert.equal(appSource.includes("throw new Error(\"Sign in with a real Supabase account to use admin or reseller actions.\");"), true, "Protected mutations must fail with a clear local-dev auth message.");
assert.equal(appSource.includes("const SERVER_MONITOR_ENABLED ="), true, "Frontend must expose a server monitoring toggle for local diagnostics.");
assert.equal(appSource.includes("async function monitoredFetch("), true, "Frontend must route Supabase requests through a monitored fetch wrapper.");
assert.equal(appSource.includes("const SUPABASE_REST_PAGE_SIZE = 1000"), true, "Supabase REST reads must page around the project row cap.");
assert.equal(appSource.includes("async function fetchSupabaseRows("), true, "Supabase GET helpers must share paginated row loading.");
assert.equal(appSource.includes('params.set("offset", String(offset));'), true, "Paginated Supabase reads must advance with offset.");
assert.equal(appSource.includes("console.info(\"[server-monitor]\""), true, "Frontend monitoring must log request and response metadata.");
assert.equal(appSource.includes("response.clone().text()"), true, "Frontend monitoring must capture failing response bodies without consuming them.");
assert.equal(appSource.includes("Promise.allSettled(tasks.map"), true, "Protected data loading must preserve successful feeds when one protected request fails.");
assert.equal(appSource.includes("Some protected data could not load:"), true, "Partial protected data failures must be visible without hiding loaded inventory.");
assert.equal(appSource.includes('"requests"'), true, "Admin routes must include a dedicated Requests page.");
assert.equal(appSource.includes('"requests-review"'), true, "Admin order workspace must expose a review page.");
assert.equal(appSource.includes('"requests-payment"'), true, "Admin order workspace must expose a payment page.");
assert.equal(appSource.includes('"requests-supplier"'), true, "Admin order workspace must expose a supplier page.");
assert.equal(appSource.includes('"requests-completed"'), true, "Admin order workspace must expose a completed page.");
assert.equal(appSource.includes('"applications"'), true, "Admin routes must include a dedicated Applications page.");
assert.equal(appSource.includes("function publicHomePage("), true, "Public home must have a dedicated content page renderer.");
assert.equal(appSource.includes("function flyerCarousel("), true, "Home must render a lightweight flyer carousel.");
assert.equal(appSource.includes("function storyCarousel("), true, "Home must render latest stories.");
assert.equal(appSource.includes("function storyDetailPage("), true, "Story detail route must render a story page.");
assert.equal(appSource.includes('"store": publicHomePage'), true, "Store route must render the public content home.");
assert.equal(appSource.includes('"story": storyDetailPage'), true, "Story route must render story details.");
assert.equal(appSource.includes('["Products", "product-flyers", ["product-flyers", "product-flyer"]]'), true, "Public navigation must point Products to the public flyer pages, not reseller catalog products.");
assert.equal(appSource.includes('href="#catalog"'), false, "Legacy catalog CTAs must not point to the removed in-page catalog anchor.");
assert.equal(appSource.includes('safeRoute === "catalog" || safeRoute === "products"'), true, "Legacy catalog/product CTAs must route to the public product flyer page.");
assert.equal(appSource.includes("<h2>Field Records</h2>"), true, "Homepage stories section should use the new editorial heading.");
assert.equal(appSource.includes('class="home-flyer-stage"'), true, "Homepage flyer hero should render a dedicated campaign stage.");
assert.equal(appSource.includes('class="home-flyer-panel campaign-surface-shadow"'), true, "Homepage flyer carousel should use one composed campaign panel instead of detached hero cards.");
assert.equal(appSource.includes('class="home-bokeh-background"'), true, "Homepage should render a bokeh background layer behind the campaign content.");
assert.equal(appSource.includes('class="public-home-shell"'), true, "Homepage should render inside a tighter editorial shell.");
assert.equal(appSource.includes('class="public-home product-flyers-page"'), true, "Public product flyers page must use the same homepage shell styling.");
assert.equal(appSource.includes("WebsiteContent.DEFAULT_PRODUCT_FLYERS"), true, "Public product flyers must have demo fallback rows when the remote flyer table is not available.");
assert.equal(appSource.includes("WebsiteContent.mergeProductFlyersWithDefaults"), true, "Default public flyers must merge with Supabase rows so the visible seeded flyers remain editable.");
assert.equal(appSource.includes("WebsiteContent.groupProductFlyersByClass"), true, "Public product flyers page must group flyers by the Word document product categories.");
assert.equal(appSource.includes("product-flyer-category"), true, "Public product flyers page must render category sections.");
assert.equal(appSource.includes('class="campaign-eyebrow"'), true, "Homepage flyer hero should render campaign metadata labels.");
assert.equal(appSource.includes("this.src='Flyer Templates/Flyer Template.jpg'"), true, "Homepage flyer image should fall back to the local flyer if uploaded media fails.");
assert.equal(appSource.includes("ENGINEERED FOR THE CONTINENT"), true, "Homepage about section should use the manifesto heading fallback.");
assert.equal(appSource.includes("Lead Flyer"), false, "Homepage copy should not expose development-sounding flyer labels.");
assert.equal(appSource.includes("Previous Signal"), false, "Homepage controls should use clean public-facing wording.");
assert.equal(appSource.includes("Open record"), false, "Story cards should use standard public-facing action text.");
assert.equal(styleSource.includes(".home-flyer-stage"), true, "Styles should define the flyer-led campaign stage.");
assert.equal(styleSource.includes("--home-max: 1288px"), true, "Homepage should use one shared max-width token for the shell.");
assert.equal(styleSource.includes(".public-home-shell"), true, "Styles should define the tighter homepage shell.");
assert.equal(styleSource.includes(".home-flyer-panel"), true, "Styles should define a unified flyer carousel panel.");
assert.equal(styleSource.includes(".home-bokeh-background"), true, "Styles should define the bokeh background layer.");
assert.equal(styleSource.includes(".campaign-surface-shadow"), true, "Styles should define the subtle premium surface shadow treatment.");
assert.equal(styleSource.includes(".campaign-actions .button"), true, "Styles should refine homepage button polish.");
assert.equal(styleSource.includes(".home-ghost-button {"), true, "Homepage secondary CTA should have a dark treatment.");
assert.equal(styleSource.includes("object-fit: contain"), true, "Homepage flyer media should fit inside the frame instead of cropping.");
assert.equal(styleSource.includes("aspect-ratio: 1 / 1"), true, "Homepage flyer frame should support poster/square campaign artwork instead of forcing a 16:9 banner.");
assert.equal(styleSource.includes("backdrop-filter: blur(18px)"), true, "Homepage glass surfaces should have a visible frosted treatment.");
assert.equal(styleSource.includes("filter: drop-shadow"), true, "Homepage buttons should have a visible nested icon hover treatment.");
assert.equal(styleSource.includes("margin-left: 50%"), false, "Homepage should not use a hero breakout hack that creates inconsistent side gutters.");
assert.equal(styleSource.includes(".story-card-tag"), true, "Styles should define campaign story tags.");
assert.equal(appSource.includes('class="catalog-section" id="catalog"'), false, "Public home must no longer render the catalogue section.");
assert.equal(appSource.includes("cart-like"), false, "Public home copy must not use shopping/cart language.");
assert.equal(appSource.includes("function adminRequests()"), true, "Admin request review must have its own focused view.");
assert.equal(appSource.includes("function adminOrderWorkspacePage("), true, "Admin orders should share one focused workspace renderer.");
assert.equal(appSource.includes("function workspaceSubnav("), true, "Order workspaces must render a local sub-navigation.");
assert.equal(appSource.includes("function adminApplications()"), true, "Reseller applications must have their own focused admin view.");
assert.equal(appSource.includes('["Requests", "requests", ["requests", "requests-all", "requests-review", "requests-payment", "requests-supplier", "requests-completed"]]'), true, "Admin navigation must expose Requests as a first-level item.");
assert.equal(appSource.includes('["Applications", "applications", ["applications"]]'), true, "Admin navigation must expose Applications as a first-level item.");
assert.equal(appSource.includes('function adminAllOrdersPage()'), true, "Admin must have an all-orders view that includes closed statuses.");
assert.equal(appSource.includes('data-action="download-all-orders-xlsx"'), true, "All orders must be exportable to Excel.");
assert.equal(appSource.includes('function adminResellers()'), true, "Reseller customers must have a separate admin section.");
assert.equal(appSource.includes("Orders & Applications"), false, "Admin navigation must not combine requests and applications into one ambiguous section.");
assert.equal(appSource.includes('data-route="admin" class="admin-return button mini"'), true, "Logged-in admins viewing the public site must get a persistent Back to Admin control.");
assert.equal(appSource.includes("function adminPublicBar()"), true, "Public admin sessions must render a dedicated return bar.");
assert.equal(appSource.includes("admin-return-bar"), true, "Public admin sessions must visibly separate admin return controls from normal navigation.");
assert.equal(appSource.includes('data-status="fulfilled"'), false, "Request review must not expose fulfillment as a one-click admin action.");
assert.equal(appSource.includes("Product Requests"), true, "Admin copy must use request language instead of ecommerce order language.");
assert.equal(appSource.includes("function adminInvitePage()"), true, "Invite-only admin onboarding must have a dedicated hidden screen.");
assert.equal(appSource.includes('data-form="homepage-flyer"'), true, "Admin site controls must include flyer manager form.");
assert.equal(appSource.includes('data-form="blog-post"'), true, "Admin site controls must include story manager form.");
assert.equal(appSource.includes('data-form="about-content"'), true, "Admin site controls must include about editor form.");
assert.equal(appSource.includes("async function saveHomepageFlyer("), true, "Flyer saves must have a dedicated handler.");
assert.equal(appSource.includes("async function saveBlogPost("), true, "Story saves must have a dedicated handler.");
assert.equal(appSource.includes('name="flyer_id"'), true, "Homepage flyer editing must retain the selected flyer id.");
assert.equal(appSource.includes('data-action="edit-homepage-flyer"'), true, "Saved homepage flyers must be clickable and editable.");
assert.equal(appSource.includes("async function updateHomepageFlyer("), true, "Homepage flyer edits must update the selected row.");
assert.equal(appSource.includes('updateAuthedSupabase("homepage_flyers"'), true, "Homepage flyer edits must persist to Supabase.");
assert.equal(appSource.includes('data-action="delete-homepage-flyer"'), true, "Homepage flyers must expose guarded deletion.");
assert.equal(appSource.includes('name="story_id"'), true, "Story editing must retain the selected story id.");
assert.equal(appSource.includes('data-action="edit-blog-post"'), true, "Saved stories must be clickable and editable.");
assert.equal(appSource.includes("async function updateBlogPost("), true, "Story edits must update the selected row.");
assert.equal(appSource.includes('updateAuthedSupabase("blog_posts"'), true, "Story edits must persist to Supabase.");
assert.equal(appSource.includes('data-action="delete-blog-post"'), true, "Stories must expose guarded deletion.");
assert.equal(appSource.includes("function bindContentAdminAction("), true, "Saved content rows must share accessible click and keyboard behavior.");
assert.equal(appSource.includes("WebsiteContent.normalizeFlyers(flyers, { includeUnpublished: state.auth.isAdmin })"), true, "Admins must be able to preview unpublished homepage flyers.");
assert.equal(styleSource.includes(".content-admin-item-actionable:hover"), true, "Clickable content rows must visibly respond on hover.");
assert.equal(styleSource.includes(".content-admin-item-actionable:focus-visible"), true, "Clickable content rows must expose a keyboard focus state.");
assert.equal(styleSource.includes(".content-editor-current-image"), true, "Content editors must show the image currently attached to the record.");
assert.equal(appSource.includes("async function saveAboutContent("), true, "About saves must have a dedicated handler.");
assert.equal(appSource.includes("async function uploadContentImage("), true, "Website content images must upload through a dedicated storage helper.");
assert.equal(appSource.includes("const SITE_CONTROL_SECTIONS"), true, "Site Controls must define a local section menu.");
assert.equal(appSource.includes("function activeSiteControlSection("), true, "Site Controls must track an active submenu section.");
assert.equal(appSource.includes("function siteControlsSubnav("), true, "Site Controls must render a local submenu.");
assert.equal(appSource.includes('data-action="site-controls-section"'), true, "Site Controls submenu buttons must switch sections without cluttering the main sidebar.");
assert.equal(appSource.includes("function siteHomepageFlyersPanel("), true, "Homepage flyers must render in a focused Site Controls panel.");
assert.equal(appSource.includes("function siteStoriesPanel("), true, "Stories must render in a focused Site Controls panel.");
assert.equal(appSource.includes("function siteProductFlyersPanel("), true, "Public product flyers must render in a focused Site Controls panel.");
assert.equal(appSource.includes("function siteAboutPanel("), true, "About content must render in a focused Site Controls panel.");
assert.equal(appSource.includes("function siteHeroThemePanel("), true, "Hero/theme/banner controls must render in a focused Site Controls panel.");
assert.equal(appSource.includes("function publicProductFlyerGalleryControls("), true, "Public product flyer editing must render the named 20-image gallery controls.");
assert.equal(appSource.includes("${publicProductFlyerGalleryControls(productFlyerEdit)}"), true, "Site controls must call the public flyer gallery editor.");
assert.equal(appSource.includes("${productFlyerImagePreview({"), false, "Site controls must not call the old undefined product flyer image preview name.");
assert.equal(appSource.includes("new_product_flyer_image_file_"), true, "Public product flyer editing must expose upload rows for new gallery images.");
assert.equal(appSource.includes("existing_product_flyer_image_file_"), true, "Public product flyer editing must let admins replace existing gallery images.");
assert.equal(appSource.includes("data-product-flyer-image-preview"), true, "Public flyer image upload rows must expose a live preview target.");
assert.equal(appSource.includes("function previewSelectedProductFlyerImage("), true, "Public flyer image uploads must update the preview as soon as a file is selected.");
assert.equal(appSource.includes('input[name^="existing_product_flyer_image_file_"], input[name^="new_product_flyer_image_file_"]'), true, "Public flyer image preview binding must cover replacement and new image uploads.");
assert.equal(appSource.includes("existing_product_flyer_image_name_"), true, "Public product flyer editing must let admins name existing gallery images.");
assert.equal(appSource.includes("existing_product_flyer_image_sku_"), true, "Public product flyer editing must let admins assign SKU/reference text per image.");
assert.equal(appSource.includes("product_flyer_cover_image"), true, "Public product flyer editing must let admins choose the cover image.");
assert.equal(appSource.includes("Legacy image preview only"), false, "Public flyer main images must not be locked as preview-only legacy images.");
assert.equal(appSource.includes("PUBLIC_PRODUCT_FLYER_IMAGE_LIMIT"), true, "Public product flyer editing must communicate the shared 20-picture limit.");
assert.equal(appSource.includes('data-form="public-product-flyer"'), true, "Site controls must expose a public product flyer form.");
assert.equal(appSource.includes("public-product-flyer-admin-card"), true, "Public product flyer editor must have a dedicated full-width admin card class.");
assert.equal(appSource.includes("async function savePublicProductFlyer("), true, "Public product flyer form must save through a dedicated handler.");
assert.equal(appSource.includes("function readablePublicProductFlyerDatabaseError("), true, "Missing public flyer table errors must be shown in plain admin-facing language.");
assert.equal(appSource.includes("state.adminContentError = readablePublicProductFlyerDatabaseError"), true, "Public flyer database failures must surface inside Site Controls.");
assert.equal(appSource.includes('name="product_flyer_id"'), true, "Public product flyer form must keep the selected flyer id while editing.");
assert.equal(appSource.includes('data-action="edit-public-product-flyer"'), true, "Site controls must let admins edit existing public product flyers.");
assert.equal(appSource.includes("async function editPublicProductFlyer("), true, "Public product flyer edits must use a dedicated edit handler.");
assert.equal(appSource.includes("async function updatePublicProductFlyer("), true, "Public product flyer edits must use a dedicated update handler.");
assert.equal(appSource.includes('updateAuthedSupabase("public_product_flyers"'), true, "Public product flyer edits must update the existing Supabase row.");
assert.equal(appSource.includes("isSeededProductFlyer("), true, "Seeded hard-coded product flyers must be detected by slug.");
assert.equal(appSource.includes("upsertAuthedSupabase(\"public_product_flyers\""), true, "Editing a seeded hard-coded product flyer must promote it to a Supabase row by slug.");
assert.equal(appSource.includes('data-action="delete-public-product-flyer"'), true, "Site controls must let admins delete public product flyer test rows.");
assert.equal(appSource.includes("async function deletePublicProductFlyer("), true, "Public product flyer deletes must use a dedicated handler.");
assert.equal(appSource.includes('deleteAuthedSupabase("public_product_flyers"'), true, "Public product flyer deletes must remove the row from Supabase.");
assert.equal(appSource.includes("state.publicProductFlyers = state.publicProductFlyers.filter"), true, "Public product flyer deletes must remove the item from local state after success.");
assert.equal(appSource.includes('fetchOptionalSupabaseResult("public_product_flyer_images"'), true, "Public bootstrap must fetch public flyer image rows separately.");
assert.equal(appSource.includes('fetchAuthedSupabase("public_product_flyer_images"'), true, "Admin bootstrap must fetch all public flyer image rows.");
assert.equal(appSource.includes('insertAuthedSupabase(\n      "public_product_flyer_images"'), true, "Public product flyer saves must insert named gallery image rows.");
assert.equal(appSource.includes('updateAuthedSupabase(\n      "public_product_flyer_images"'), true, "Public product flyer edits must update named gallery image rows.");
assert.equal(appSource.includes("PUBLIC_PRODUCT_FLYER_IMAGE_LIMIT = 20"), true, "Public flyer images must keep the 20-picture per-shoe allowance.");
assert.equal(appSource.includes("PUBLIC_PRODUCT_FLYER_EMPTY_IMAGE_SLOTS = 3"), true, "Public flyer editor must avoid rendering all 20 empty upload rows at once.");
assert.equal(appSource.includes("Math.min(remaining, PUBLIC_PRODUCT_FLYER_EMPTY_IMAGE_SLOTS)"), true, "Public flyer editor must cap visible empty upload slots.");
assert.equal(appSource.includes("WebsiteContent.buildProductFlyerImageUpdatePayload"), true, "Public flyer image edits must use an update payload that preserves creator metadata.");
assert.equal(appSource.includes('if (formName === "public-product-flyer") {'), true, "Public product flyer form must have a dedicated submit branch.");
assert.equal(appSource.includes("return;\n      }\n      if (formName === \"about-content\")"), true, "Public product flyer submit must not fall through to the global rerender that can wipe file previews.");
assert.equal(styleSource.includes(".public-product-flyer-gallery-row {\n    grid-template-columns: 1fr;"), true, "Public flyer gallery rows must collapse on mobile instead of squeezing inputs.");
assert.equal(styleSource.includes("aspect-ratio: 1 / 1"), true, "Public flyer editor previews must use stable square image boxes.");
assert.equal(styleSource.includes("object-fit: contain"), true, "Public flyer editor previews must show the whole uploaded shoe image.");
assert.equal(appSource.includes("function productFlyersPage("), true, "Public product flyer listing page must exist.");
assert.equal(appSource.includes("function productFlyerDetailPage("), true, "Public product flyer detail page must exist.");
assert.equal(appSource.includes('data-route="product-flyer"'), true, "Public product flyer cards must route to public flyer detail pages.");
assert.equal(appSource.includes(">View shoe</button>"), true, "Public product flyer cards should use shoe language for visitors.");
assert.equal(appSource.includes(">View flyer</button>"), false, "Public product flyer cards should not use internal flyer language for visitors.");
assert.equal(styleSource.includes(".product-flyer-grid"), true, "Public product flyer listing must have dedicated styling.");
assert.equal(styleSource.includes(".product-flyer-category"), true, "Public product flyer category sections must have dedicated styling.");
assert.equal(styleSource.includes(".product-flyer-gallery-item"), true, "Public product flyer detail must style named image gallery items.");
assert.equal(styleSource.includes(".public-product-flyer-gallery-row"), true, "Public product flyer admin editor must style gallery rows.");
assert.equal(styleSource.includes(".public-product-flyer-admin-card"), true, "Public product flyer editor must have dedicated layout styling.");
assert.equal(styleSource.includes("grid-column: 1 / -1"), true, "Public product flyer editor must span the Site Controls grid so copy is not clipped.");
assert.equal(styleSource.includes("overflow-wrap: anywhere"), true, "Admin product flyer copy must wrap instead of clipping inside narrow cards.");
assert.match(styleSource, /\.gallery-thumb img\s*\{[\s\S]*object-fit:\s*contain/i, "Product detail gallery thumbnails must show the whole shoe image instead of cropping it.");
assert.equal(styleSource.includes(".site-controls-workspace"), true, "Site Controls must use a submenu workspace layout.");
assert.equal(styleSource.includes(".site-controls-panel"), true, "Site Controls focused panels must have dedicated styling.");
assert.equal(productFlyerPageSource.includes("base_price"), false, "Public flyer pages must not expose reseller pricing.");
assert.equal(appSource.includes("Website Content"), true, "Admin page title should reflect content management.");
assert.equal(appSource.includes('data-form="admin-invite"'), true, "Team page must let admins create private invite links.");
assert.equal(appSource.includes('data-action="copy-admin-invite"'), true, "Invite creation must expose a copy action for the generated link.");
assert.equal(appSource.includes('data-action="revoke-admin-invite"'), true, "Team page must let admins revoke pending invites.");
assert.equal(appSource.includes('invokePublicRpc("lookup_admin_invite"'), true, "Invite landing page must validate the hidden invite token before login.");
assert.equal(appSource.includes('invokeAuthedRpc("claim_admin_invite"'), true, "Invite redemption must promote the signed-in account after Google login.");
assert.equal(appSource.includes("buildAdminInviteUrl(token)"), true, "Team page must generate a private admin invite link for the recipient.");
assert.equal(appSource.includes("<h2>Live Inventory</h2>"), false, "Reseller portal must not present ordering as a live inventory table.");
assert.equal(appSource.includes("<th>Exact Stock</th>"), false, "Reseller portal must not expose exact-stock table headings.");
assert.equal(appSource.includes("Add live inventory lines"), false, "Reseller draft copy must describe products, not inventory lines.");
assert.equal(appSource.includes("reseller-product-card"), true, "Reseller portal must render ecommerce-style product cards.");
assert.equal(appSource.includes('"reseller-product": resellerProductOrderPage'), true, "Reseller products must open a dedicated ordering page.");
assert.equal(appSource.includes('"request-confirmation": requestConfirmationPage'), true, "Submitted reseller requests must open a dedicated confirmation page.");
assert.equal(appSource.includes('data-action="open-reseller-product"'), true, "Reseller product cards must be clickable.");
assert.equal(appSource.includes("function productVisualCarousel("), true, "Catalogue cards must use a reusable image carousel.");
assert.equal(appSource.includes("data-action=\"catalog-image-step\""), true, "Catalogue cards must expose image carousel arrows.");
assert.equal(appSource.includes("state.catalogImageSelection"), true, "Catalogue card image arrows must keep per-card image state.");
assert.equal(resellerProductCardSource.includes("canOrder"), false, "Reseller browse cards must not reference detail-only ordering state.");
assert.equal(appSource.includes("Orders.availableInventoryRows(inventoryRows())"), true, "Reseller shop must only show rows that are actually available to order.");
assert.equal(appSource.includes("Orders.visibleShopProductGroups(rows"), true, "Reseller shop must group SKU rows into product cards before rendering.");
assert.equal(appSource.includes("Orders.buildInventorySearchSuggestions"), true, "Reseller search must provide model and SKU suggestions.");
assert.equal(appSource.includes("renderResellerSearchResults()"), true, "Reseller search rerenders must restore input focus.");
assert.equal(appSource.includes("input.focus({ preventScroll: true })"), true, "Reseller search must keep keyboard focus after results update.");
assert.equal(appSource.includes("data-action=\"open-search-suggestion\""), true, "Reseller search suggestions must open the selected product.");
assert.equal(appSource.includes("productLimit: Math.max(24, state.products.length || 21)"), true, "Reseller shop must show all source-backed products while still limiting per-product choices.");
assert.equal(appSource.includes("function resellerBulkOrderMatrix("), true, "Reseller shop must use a bulk size matrix for wholesale ordering.");
assert.equal(appSource.includes("data-action=\"select-reseller-colour\""), true, "Reseller shop must let buyers choose colours visually before ordering sizes.");
assert.equal(appSource.includes("data-action=\"add-bulk-order\""), true, "Reseller shop must add selected size quantities as a bulk order action.");
assert.equal(appSource.includes("data-bulk-qty-input"), true, "Reseller shop must use size quantity inputs in the bulk matrix.");
assert.equal(appSource.includes("colour-dot"), true, "Reseller colour chips must use simple swatches instead of image tiles.");
assert.equal(appSource.includes("product-facts"), true, "Reseller cards must show compact product facts.");
assert.equal(appSource.includes("units exact stock"), true, "Reseller cards must show the exact stock total.");
assert.equal(appSource.includes("in stock"), true, "Reseller size rows must show exact stock counts.");
assert.equal(appSource.includes("builder-colour-order-card"), true, "Reseller product ordering must use color cards with size inputs inside.");
assert.equal(appSource.includes("builder-colour-order-list"), true, "Reseller product ordering must list color cards as the main order form.");
assert.equal(appSource.includes("builder-size-row"), true, "Reseller product ordering must use form-style size quantity rows.");
assert.equal(appSource.includes("setRoute(\"request-confirmation\")"), true, "Order submission must navigate to the confirmation page.");
assert.equal(appSource.includes('invokeAuthedRpc("submit_order_request"'), true, "Order submission must create the order and its items in one database transaction.");
assert.equal(appSource.includes('invokeAuthedRpc("transition_order_request"'), true, "Every order transition must run in one database transaction.");
assert.equal(appSource.includes('invokeAuthedRpc("submit_reseller_application"'), true, "Reseller applications must be submitted through the one-row transactional workflow.");
assert.equal(appSource.includes('invokeAuthedRpc("publish_site_controls"'), true, "Site controls must publish atomically.");
assert.equal(appSource.includes('invokeAuthedRpc("save_product_catalog"'), true, "Product catalog rows must save atomically after storage upload.");
assert.equal(appSource.includes('invokeAuthedRpc("review_reseller_application"'), true, "Reseller review must update the application and profile atomically.");
assert.equal(appSource.includes('invokeAuthedRpc("reset_inventory_from_import"'), true, "Inventory imports must reset and replace stock in one database transaction.");
assert.equal(appSource.includes('invokeAuthedRpc("adjust_inventory_stock"'), true, "Manual stock corrections must use the audited database workflow.");
assert.equal(appSource.includes('data-action="save-stock-adjustment"'), true, "Admin product rows must expose manual stock correction controls.");
assert.equal(appSource.includes('type: "catalog_seed_inventory"'), false, "Inventory uploads must not create or seed products.");
assert.equal(styleSource.includes(".manual-stock-row"), true, "Manual stock controls must have responsive layout styles.");
assert.equal(appSource.includes("loadProtectedDataInBackground();"), true, "Order submission must not block confirmation routing on protected data refresh.");
const accountProfileSaveSource = sourceBetween("async function handleAccountProfileSave(", "async function handleAccountPasswordSave(");
const orderSubmitSource = sourceBetween("async function handleOrderSubmit(", "async function handleApplicationSubmit(");
assert.equal(accountProfileSaveSource.includes('invokeAuthedRpc("set_reseller_directory_listing"'), true, "Directory visibility must save from Account settings.");
assert.equal(orderSubmitSource.includes('invokeAuthedRpc("set_reseller_directory_listing"'), false, "Order submission must not run unrelated directory updates after creating an order.");
assert.equal(appSource.includes("function refreshWorkflowData()"), true, "Order and application screens must refresh automatically.");
assert.equal(appSource.includes("function workflowActionDialog()"), true, "Risky workflow transitions must require an explicit confirmation form.");
assert.equal(appSource.includes("adminOrderActionButtons(record)"), true, "Admin request cards must render workflow-driven action buttons.");
assert.equal(appSource.includes('<p class="mono">SKU:'), false, "Reseller order summary must not expose backend SKU labels.");
assert.equal(appSource.includes("Available Options"), false, "Reseller metrics must use buyer-friendly language instead of backend option labels.");
assert.equal(appSource.includes(".inventory-panel, .order-sidebar"), false, "Functional reseller panels must not be hidden behind reveal observer opacity.");
assert.equal(appSource.includes('class="product-overview"'), true, "Admin products page must still render product overview sections.");
assert.equal(/function applyRevealMotion\(\)[\s\S]*document\.querySelectorAll\([\s\S]*\.product-overview/.test(appSource), false, "Admin product panels must not be hidden behind reveal observer opacity.");
assert.equal(appSource.includes("const activeProductModels = productModels.filter((model) => model.published);"), true, "Admin products page must default to the published source-truth product set.");
assert.equal(appSource.includes("archived products are hidden from this view"), true, "Admin products page must explain that archived products are intentionally hidden.");
assert.equal(appSource.includes("data-action=\"save-product-price\""), true, "Admin products page must let admins save prices on existing products.");
assert.equal(appSource.includes('class="admin-stock-details"'), true, "Admin product size and stock details must be collapsible.");
assert.equal(appSource.includes("const sizes = matrix.sizes.slice(0, 6);"), false, "Admin stock matrix must not hide sizes after the first six.");
assert.equal(appSource.includes(".slice(0, 4)\n          .map(\n            (row) => `\n              <div class=\"stock-matrix-row\">"), false, "Admin stock matrix must not hide colour stock rows after the first four.");
assert.equal(appSource.includes("Showing top stock rows"), false, "Admin stock matrix must not claim it is hiding stock rows.");
assert.equal(appSource.includes("--stock-size-count"), true, "Admin stock matrix must size columns dynamically for all size options.");
assert.equal(appSource.includes("activeProducts\n              .slice(0, 6)"), false, "Admin product overview must not hide active products after the first six.");
assert.equal(appSource.includes("async function updateAuthedSupabase("), true, "Admin price edits must use authenticated Supabase updates.");
assert.equal(appSource.includes("async function handleProductPriceUpdate("), true, "Admin price edits must have a dedicated handler.");
assert.equal(appSource.includes("Reset All Stock"), true, "Admin inventory page must expose a clear stock reset control.");
assert.equal(appSource.includes("Type RESET STOCK to confirm"), true, "Stock reset must require typed confirmation.");
assert.equal(appSource.includes("async function handleStockReset("), true, "Admin stock reset must have a dedicated handler.");
assert.equal(appSource.includes("async function patchAuthedSupabaseMinimal("), true, "Bulk stock reset must use minimal PATCH responses.");
assert.equal(appSource.includes('patchAuthedSupabaseMinimal("inventory", "id=not.is.null"'), true, "Stock reset must zero every inventory row.");
assert.equal(appSource.includes("source: \"manual_stock_reset\""), true, "Stock reset must mark inventory rows with a reset source.");
assert.equal(appSource.includes("async function depleteSubmittedOrderStock("), false, "Order submission must not deplete stock immediately.");
assert.equal(appSource.includes("source: \"order_submitted\""), false, "Submitted orders must not change inventory immediately.");
assert.equal(appSource.includes("AdminOrders.buildApprovalInventoryAdjustments"), false, "Admin approval must not reserve stock through sequential browser updates.");
assert.equal(appSource.includes('invokeAuthedRpc("transition_order_request"'), true, "Supply approval must reserve stock through the transactional database workflow.");
assert.equal(appSource.includes("\"current-orders\": currentOrdersPage"), true, "Reseller route map must expose a dedicated current orders page.");
assert.equal(appSource.includes("\"expected-orders\": expectedOrdersPage"), true, "Reseller route map must expose a dedicated expected orders page.");
assert.equal(appSource.includes("fulfillment: fulfillmentStatusPage"), true, "Reseller route map must expose a fulfillment status page.");
assert.equal(appSource.includes("order: orderDetailPage"), true, "Route map must expose a shared order detail page.");
assert.equal(appSource.includes("function orderDetailPage()"), true, "Order detail page must exist.");
assert.equal(appSource.includes('data-action="download-order-xlsx"'), true, "Order detail must expose supplier XLSX export.");
assert.equal(appSource.includes('data-action="download-order-csv"'), true, "Order detail must expose supplier CSV export.");
const orderRequestSelect = appSource.match(/const workflowQuery = "([^"]+)"/)?.[1] || "";
assert.equal(orderRequestSelect.includes("supplier_exported_at"), true, "Order request fetch must include supplier_exported_at so export status survives refresh.");
["approved_at", "paid_at", "supplier_submitted_at", "processing_at", "shipped_at", "fulfilled_at", "expected_fulfillment_date", "invoice_number", "payment_reference", "payment_note"].forEach((column) => {
  assert.equal(orderRequestSelect.includes(column), true, `Order request fetch must include workflow column ${column}.`);
});
assert.equal(appSource.includes('"select=id,reseller_id,status,notes,admin_notes,created_at,updated_at&order=created_at.desc&limit=100"'), true, "Order request loading must retain a backward-compatible fallback when workflow columns are not deployed yet.");
assert.equal(appSource.includes("Stock updates only after approval."), true, "Reseller messaging must match approval-based stock deduction.");
assert.equal(appSource.includes("Price pending"), true, "Reseller shop must show pending price instead of a false zero price.");
assert.equal(appSource.includes('<div><button disabled>Prev</button><button class="active">1</button><button>2</button><button>3</button><button>Next</button></div>'), false, "Catalog pager must not be static fake controls.");
assert.equal(pagerSource.includes("<button"), false, "Reseller shop summary must not render fake pager buttons.");
assert.equal(pagerSource.includes("pager-count"), true, "Reseller shop summary should render as a simple count row when there is no real pagination.");
assert.equal(appSource.includes("data-action=\"catalog-page\""), true, "Catalog pager buttons must have real page actions.");
assert.equal(appSource.includes("data-action=\"select-gallery-image\""), true, "Product detail thumbnails must be wired as selectable gallery buttons.");
assert.equal(appSource.includes("[data-product-detail-main] .product-visual"), true, "Product detail thumbnail clicks must target the main product visual.");
assert.equal(appSource.includes("photo.setAttribute(\"src\", imageUrl);"), true, "Product detail thumbnail clicks must update the main product photo.");
assert.equal(selectorGroupSource.includes("<button"), false, "Public detail colour and size values must not render as dead buttons.");
assert.equal(selectorGroupSource.includes("selector-chip"), true, "Public detail colour and size values should render as non-interactive chips.");
assert.equal(appSource.includes("Colour Review"), true, "Admin products page must include the Colour Review section.");
assert.equal(appSource.includes("product_colour_mappings"), true, "Colour Review must save against product_colour_mappings.");
assert.equal(appSource.includes("original_colour"), true, "Colour Review wiring must preserve original_colour keys.");
assert.equal(indexSource.includes('rel="icon"'), true, "Document head must declare a favicon to avoid localhost favicon 404s.");
assert.equal(indexSource.includes("Oswald"), true, "Homepage redesign should load the condensed display font.");
assert.equal(indexSource.includes("irunsvan-public-flyer-gallery-v1"), true, "Index should bump public asset cache keys for public flyer gallery updates.");
assert.equal(indexSource.includes("irunsvan-order-email-v1"), false, "Index must not keep the stale order email cache key after public flyer gallery updates.");
assert.equal(indexSource.includes("irunsvan-order-export-v3"), false, "Index must not keep the stale order export cache key after email updates.");
assert.equal(indexSource.includes("irunsvan-public-flyer-editor-v2"), false, "Index must not keep the stale flyer editor cache key after order export updates.");
assert.equal(indexSource.includes("irunsvan-home-terra-light-v1"), false, "Index must not keep the stale homepage cache key after flyer editor updates.");
assert.equal(appSource.includes("object-fit: contain"), false, "Image sizing changes must live in CSS, not inline styles.");
assert.equal(emailDispatcherSource.includes("IRUNSVAN AFRICA"), true, "Order emails must preserve the branded reseller-facing HTML template.");
assert.equal(emailDispatcherSource.includes("rpc/claim_notification_outbox"), true, "Email workers must atomically claim queued notifications before sending.");
assert.equal(emailDispatcherSource.includes('status: "in.(pending,failed)"'), false, "Email workers must not race by selecting unclaimed pending rows directly.");
assert.equal(appSource.includes("html: body.html"), false, "The browser must not be able to submit arbitrary email HTML.");
assert.equal(appSource.includes("orderOperationalDetails"), true, "Order pages must expose operational payment, invoice, date, and decision details.");
assert.equal(appSource.includes('<button data-route="terms">Terms</button>'), true, "The public footer must expose the Terms page.");
assert.equal(appSource.includes("follow up before this request goes stale"), true, "Old open requests must show an operational follow-up warning.");
assert.equal(appSource.includes("bindCatalogImageStepEvents(root)"), true, "Search result carousels must be rebound after partial search rendering.");
const oldBrandSlug = "ivan" + "srun";
const oldBrandName = "Ivan" + "srun";
assert.equal(indexSource.includes(`${oldBrandSlug}-google-auth-v1`), false, "Index must not keep the stale Google OAuth cache key after Irunsvan brand correction.");
assert.equal(indexSource.includes(`${oldBrandName} Africa`), false, "Visible document metadata must use Irunsvan Africa branding.");
assert.equal(appSource.includes(`${oldBrandName} Africa`), false, "Frontend copy must use Irunsvan Africa branding.");
assert.equal(appSource.includes(`${oldBrandName} reseller`), false, "Frontend fallback company copy must use Irunsvan reseller branding.");
assert.equal(indexSource.includes(`${oldBrandSlug}-real-auth-v1`), false, "Index must not keep the stale real-auth cache key after Google OAuth login.");
assert.equal(indexSource.includes(`${oldBrandSlug}-stock-reset-v1`), false, "Index must not keep the stale stock reset cache key after Google OAuth login.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v3`), false, "Index must not keep the stale reseller detail cache key after stock reset and depletion fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v2`), false, "Index must not keep the stale reseller detail runtime cache key after layout fix.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v1`), false, "Index must not keep the stale reseller detail cache key after runtime fix.");
assert.equal(indexSource.includes(`${oldBrandSlug}-bulk-order-v1`), false, "Index must not keep the stale bulk-order cache key after reseller product detail UI fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-auth-stock-v2`), false, "Index must not keep the stale auth stock cache key after bulk-order UI fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-ops-repair-v1`), false, "Index must not keep the stale operations cache key after auth and stock visibility fixes.");
assert.equal(indexSource.includes("operations-products.js"), true, "Index must load the operations product view-model helper before app.js.");
assert.equal(indexSource.includes("order-export.js"), true, "Index must load the order export helper before app.js.");
assert.equal(indexSource.includes("xlsx.full.min.js"), false, "XLSX import library must be lazy-loaded only when admin imports need it.");
assert.equal(indexSource.includes("jszip.min.js"), false, "JSZip import library must be lazy-loaded only when admin imports need it.");
assert.equal(appSource.includes("async function ensureImportLibraries("), true, "Admin imports must load spreadsheet/archive libraries on demand.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v4`), false, "Index must not keep the stale reseller portal v4 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v3`), false, "Index must not keep the stale reseller portal v3 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v2`), false, "Index must not keep the stale reseller portal v2 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-clear-products-v1`), false, "Index must not keep the stale reseller portal cache key.");
assert.equal(staticServerSource.includes("response.on(\"finish\""), true, "Static server must log each response for local request monitoring.");
assert.equal(staticServerSource.includes("console.log(`[static-server]"), true, "Static server logs must emit structured monitoring lines.");
assert.equal(staticServerSource.includes("/__dev/prelogin"), false, "Static server must not expose a dev-only test prelogin endpoint.");
assert.equal(staticServerSource.includes("ENABLE_TEST_LOGIN"), false, "Static server must not contain a test-login feature flag.");
assert.equal(staticServerSource.includes(`${oldBrandSlug}_auth_session`), false, "Static server must not write auth sessions.");
["AdminTest!2026", "OpsAdmin!2026", "ResellerTest!2026", "PendingTest!2026"].forEach((password) => {
  assert.equal(appSource.includes(password), false, `Frontend must not contain committed password ${password}.`);
  assert.equal(staticServerSource.includes(password), false, `Static server must not contain committed password ${password}.`);
  assert.equal(createTestAdminsSource.includes(password), false, `Test account setup must not contain committed password ${password}.`);
});
assert.equal(createTestAdminsSource.includes("passwordEnv"), true, "Test account setup must source passwords from environment variables.");

console.log("app-wiring tests passed");
