const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const appSource = readFileSync(join(__dirname, "..", "src", "app.js"), "utf8");
const indexSource = readFileSync(join(__dirname, "..", "index.html"), "utf8");
const staticServerSource = readFileSync(join(__dirname, "..", "scripts", "serve-static.js"), "utf8");
const authSource = readFileSync(join(__dirname, "..", "src", "auth.js"), "utf8");
const supabaseClientSource = readFileSync(join(__dirname, "..", "src", "supabase-client.js"), "utf8");
const createTestAdminsSource = readFileSync(join(__dirname, "..", "scripts", "create-test-admins.js"), "utf8");
const resellerProductCardSource = appSource.match(/function resellerProductCard\([\s\S]*?\n}\n\nfunction resellerColourGroups/)?.[0] || "";

assert.equal(appSource.includes("<button>View all</button>"), false, "View all buttons must navigate or trigger an action.");
assert.equal(appSource.includes('<button class="button mini">Approve</button>'), false, "Approve buttons must use real approval actions.");
assert.equal(appSource.includes('<button class="button mini secondary">Reject</button>'), false, "Reject buttons must use real rejection actions.");
assert.equal(appSource.includes('<button class="button secondary">View Template</button>'), false, "Email template buttons must open a real preview.");
assert.equal(appSource.includes("Saved only in this browser"), false, "Product saves must not fall back to browser-only data.");
assert.equal(appSource.includes("Product draft is visible locally"), false, "Product saves must fail loudly instead of creating local-only products.");
assert.equal(appSource.includes('<p class="detail-price">${money(product.base_price)}</p>'), false, "Public product detail must not show prices.");
assert.equal(appSource.includes("<strong>${money(product.base_price)}</strong>"), false, "Public product cards must not show prices.");
assert.equal(appSource.includes("Price: Low to High"), false, "Public catalogue must not offer price sorting.");
assert.equal(appSource.includes("Price Range"), false, "Public catalogue must not expose price filtering.");
assert.equal(appSource.includes("Public browsing shows product information and pricing"), false, "Public catalogue copy must not promise public pricing.");
assert.equal(appSource.includes('${inputField("Product Type", "product_type", "shoe")}'), true, "Admin product form must let the admin choose product type.");
assert.equal(appSource.includes("product_type: data.get(\"product_type\")"), true, "Product saves must use the admin-entered product type.");
assert.equal(appSource.includes("LOGIN_BYPASS"), false, "Frontend must not include login bypass logic.");
assert.equal(appSource.includes("buildLocalAdminAuthState"), false, "Frontend must not build fake admin auth state.");
assert.equal(appSource.includes("resolveBypassAuthState"), false, "Frontend must not restore bypass auth state.");
assert.equal(appSource.includes("dev-admin-login"), false, "Login page must not expose a dev admin login action.");
assert.equal(appSource.includes("/__dev/prelogin"), false, "Login page must not link to prelogin endpoints.");
assert.equal(appSource.includes("Preview admin shell"), false, "Login page must not expose admin preview shell access.");
assert.equal(appSource.includes('data-action="google-login"'), true, "Login page must expose Google OAuth login.");
assert.equal(appSource.includes("function handleGoogleLogin()"), true, "Google OAuth login must have a dedicated handler.");
assert.equal(appSource.includes("SupabaseClient.signInWithOAuth({"), true, "Google login must use Supabase OAuth instead of bypass logic.");
assert.equal(appSource.includes("signup: signupPage"), true, "Normal email account creation must have a dedicated signup route.");
assert.equal(appSource.includes("function signupPage()"), true, "Signup page must render a first-class email account creation form.");
assert.equal(appSource.includes('["Create account", "signup"]'), true, "Login must expose normal email account creation.");
assert.equal(appSource.includes('["Create Account", "signup", ["signup"]]'), true, "Public navigation must expose normal email account creation.");
assert.equal(appSource.includes('inputField("Confirm Password", "password_confirm"'), true, "Signup must require password confirmation.");
assert.equal(appSource.includes("state.signupConfirmationEmail = email;"), true, "Signup must handle email confirmation before application submission.");
assert.equal(appSource.includes('["Back to public site", "store"]'), true, "Admin login should point back to the public site instead of reseller application.");
assert.equal(appSource.includes("SupabaseClient.consumeOAuthSessionFromUrl()"), true, "Startup must consume Supabase OAuth callback sessions.");
assert.equal(appSource.includes("const hasOAuthError = Boolean(oauthResult.error || oauthError);"), true, "OAuth error handling must be explicit during startup.");
assert.equal(appSource.includes('window.history.replaceState({}, "", `${window.location.pathname}${MobileNavigation.buildRouteUrl(state.route)}`);'), true, "OAuth errors must clean the visible URL before routing.");
assert.equal(appSource.includes("if (!hasOAuthError) {"), true, "OAuth errors must not fall through to the hash-based route restore.");
assert.equal(supabaseClientSource.includes("function buildOAuthUrl("), true, "Supabase client must build provider OAuth authorize URLs.");
assert.equal(supabaseClientSource.includes("function authErrorMessage("), true, "Supabase client must normalize auth provider and credential errors.");
assert.equal(supabaseClientSource.includes("function oauthResultFromSearch("), true, "Supabase client must inspect OAuth callback query parameters.");
assert.equal(supabaseClientSource.includes("function oauthSessionFromHash("), true, "Supabase client must parse OAuth callback hash sessions.");
assert.equal(supabaseClientSource.includes("error_code"), true, "OAuth error_code must be treated as a callback parameter.");
assert.equal(appSource.includes('searchParams.delete("error_code")'), true, "OAuth redirect URLs must not keep stale error_code query parameters.");
assert.equal(authSource.includes("buildDevAdminAuthState"), false, "Auth module must not export fake dev admin state.");
assert.equal(appSource.includes("loadCatalog();\ninitAuth();"), false, "Startup must not fire catalog and auth without explicit orchestration.");
assert.equal(appSource.includes("await loadCatalog();\n  await initAuth();"), false, "OAuth callback routing must not wait for the public catalog before auth restore.");
assert.equal(appSource.includes("const catalogLoad = loadCatalog();"), true, "Startup must begin catalog loading without blocking auth restore.");
assert.equal(appSource.includes("await initAuth({ loadProtected: false });"), true, "OAuth callback routing must restore auth before protected data loading.");
assert.equal(appSource.includes("state.authBootstrapPending = false;"), true, "Auth bootstrap screen must be cleared before background protected data loading.");
assert.equal(appSource.includes("loadProtectedData().catch"), true, "Protected data should load in the background after sign-in routing.");
assert.equal(appSource.includes('const desktopItems = portalMode === "public" ? publicNavItems : portalMode === "reseller" ? resellerNavItems : [];'), true, "Admin workspace should not duplicate the full top navigation.");
assert.equal(appSource.includes("const resellerNavItems ="), true, "Reseller workspace should use a smaller dedicated top navigation.");
assert.equal(appSource.includes('if (state.auth.isPending) {'), true, "Pending users need a distinct workspace menu.");
assert.equal(appSource.includes('const url = `${window.location.pathname}${MobileNavigation.buildRouteUrl(nextRoute, historyState)}`;'), true, "Route writes must clear stale search params when changing pages.");
assert.equal(appSource.includes('const cleanUrl = `${window.location.pathname}${MobileNavigation.buildRouteUrl(nextRoute, { productId: state.selectedProductId })}`;'), true, "Route sync must clear stale search params when restoring hashes.");
assert.equal(appSource.includes("const restored = await SupabaseClient.restoreAuthState({ url: SUPABASE_URL, key: SUPABASE_KEY });"), true, "Startup must restore real Supabase sessions before protected data loading.");
assert.equal(supabaseClientSource.includes("if (!session?.access_token) return { session: null, user: null, profile: null };"), true, "Auth restore must not create protected access without a real Supabase session.");
assert.equal(appSource.includes("Sign in as a test reseller"), false, "Reseller portal must not mention test-session login paths.");
assert.equal(appSource.includes("function requireAuthedSession()"), true, "Protected mutations must require a real Supabase session.");
assert.equal(appSource.includes("throw new Error(\"Sign in with a real Supabase account to use admin or reseller actions.\");"), true, "Protected mutations must fail with a clear local-dev auth message.");
assert.equal(appSource.includes("const SERVER_MONITOR_ENABLED ="), true, "Frontend must expose a server monitoring toggle for local diagnostics.");
assert.equal(appSource.includes("async function monitoredFetch("), true, "Frontend must route Supabase requests through a monitored fetch wrapper.");
assert.equal(appSource.includes("const SUPABASE_REST_PAGE_SIZE = 1000"), true, "Supabase REST reads must page around the project row cap.");
assert.equal(appSource.includes("async function fetchSupabaseRows("), true, "Supabase GET helpers must share paginated row loading.");
assert.equal(appSource.includes('params.set("offset", String(offset));'), true, "Paginated Supabase reads must advance with offset.");
assert.equal(appSource.includes("console.info(\"[server-monitor]\""), true, "Frontend monitoring must log request and response metadata.");
assert.equal(appSource.includes("response.clone().text()"), true, "Frontend monitoring must capture failing response bodies without consuming them.");
assert.equal(appSource.includes("Promise.allSettled(tasks.map"), true, "Protected data loading must preserve successful feeds when one protected request fails.");
assert.equal(appSource.includes("Some protected data could not load:"), true, "Partial protected data failures must be visible without hiding loaded inventory.");
assert.equal(appSource.includes('"requests"'), true, "Admin routes must include a dedicated Requests page.");
assert.equal(appSource.includes('"applications"'), true, "Admin routes must include a dedicated Applications page.");
assert.equal(appSource.includes("function adminRequests()"), true, "Admin request review must have its own focused view.");
assert.equal(appSource.includes("function adminApplications()"), true, "Reseller applications must have their own focused admin view.");
assert.equal(appSource.includes('["Requests", "requests", ["requests"]]'), true, "Admin navigation must expose Requests as a first-level item.");
assert.equal(appSource.includes('["Applications", "applications", ["applications"]]'), true, "Admin navigation must expose Applications as a first-level item.");
assert.equal(appSource.includes("Orders & Applications"), false, "Admin navigation must not combine requests and applications into one ambiguous section.");
assert.equal(appSource.includes('data-route="admin" class="admin-return button mini"'), true, "Logged-in admins viewing the public site must get a persistent Back to Admin control.");
assert.equal(appSource.includes("function adminPublicBar()"), true, "Public admin sessions must render a dedicated return bar.");
assert.equal(appSource.includes("admin-return-bar"), true, "Public admin sessions must visibly separate admin return controls from normal navigation.");
assert.equal(appSource.includes('data-status="fulfilled"'), false, "Request review must not expose fulfillment as a one-click admin action.");
assert.equal(appSource.includes("Product Requests"), true, "Admin copy must use request language instead of ecommerce order language.");
assert.equal(appSource.includes("function adminInvitePage()"), true, "Invite-only admin onboarding must have a dedicated hidden screen.");
assert.equal(appSource.includes('data-form="admin-invite"'), true, "Team page must let admins create private invite links.");
assert.equal(appSource.includes('data-action="copy-admin-invite"'), true, "Invite creation must expose a copy action for the generated link.");
assert.equal(appSource.includes('data-action="revoke-admin-invite"'), true, "Team page must let admins revoke pending invites.");
assert.equal(appSource.includes('invokePublicRpc("lookup_admin_invite"'), true, "Invite landing page must validate the hidden invite token before login.");
assert.equal(appSource.includes('invokeAuthedRpc("claim_admin_invite"'), true, "Invite redemption must promote the signed-in account after Google login.");
assert.equal(appSource.includes("buildAdminInviteUrl(token)"), true, "Team page must generate a private admin invite link for the recipient.");
assert.equal(appSource.includes("<h2>Live Inventory</h2>"), false, "Reseller portal must not present ordering as a live inventory table.");
assert.equal(appSource.includes("<th>Exact Stock</th>"), false, "Reseller portal must not expose exact-stock table headings.");
assert.equal(appSource.includes("Add live inventory lines"), false, "Reseller draft copy must describe products, not inventory lines.");
assert.equal(appSource.includes("reseller-product-card"), true, "Reseller portal must render ecommerce-style product cards.");
assert.equal(appSource.includes('"reseller-product": resellerProductOrderPage'), true, "Reseller products must open a dedicated ordering page.");
assert.equal(appSource.includes('data-action="open-reseller-product"'), true, "Reseller product cards must be clickable.");
assert.equal(resellerProductCardSource.includes("canOrder"), false, "Reseller browse cards must not reference detail-only ordering state.");
assert.equal(appSource.includes("Orders.availableInventoryRows(inventoryRows())"), true, "Reseller shop must only show rows that are actually available to order.");
assert.equal(appSource.includes("Orders.visibleShopProductGroups(rows"), true, "Reseller shop must group SKU rows into product cards before rendering.");
assert.equal(appSource.includes("productLimit: Math.max(24, state.products.length || 21)"), true, "Reseller shop must show all source-backed products while still limiting per-product choices.");
assert.equal(appSource.includes("function resellerBulkOrderMatrix("), true, "Reseller shop must use a bulk size matrix for wholesale ordering.");
assert.equal(appSource.includes("data-action=\"select-reseller-colour\""), true, "Reseller shop must let buyers choose colours visually before ordering sizes.");
assert.equal(appSource.includes("data-action=\"add-bulk-order\""), true, "Reseller shop must add selected size quantities as a bulk order action.");
assert.equal(appSource.includes("data-bulk-qty-input"), true, "Reseller shop must use size quantity inputs in the bulk matrix.");
assert.equal(appSource.includes("colour-dot"), true, "Reseller colour chips must use simple swatches instead of image tiles.");
assert.equal(appSource.includes("product-facts"), true, "Reseller cards must show compact product facts.");
assert.equal(appSource.includes("units exact stock"), true, "Reseller cards must show the exact stock total.");
assert.equal(appSource.includes("in stock"), true, "Reseller size rows must show exact stock counts.");
assert.equal(appSource.includes("Approve and deduct stock"), true, "Admin approval action must make the stock change explicit.");
assert.equal(appSource.includes('<p class="mono">SKU:'), false, "Reseller order summary must not expose backend SKU labels.");
assert.equal(appSource.includes("Available Options"), false, "Reseller metrics must use buyer-friendly language instead of backend option labels.");
assert.equal(appSource.includes(".inventory-panel, .order-sidebar"), false, "Functional reseller panels must not be hidden behind reveal observer opacity.");
assert.equal(appSource.includes('class="product-overview"'), true, "Admin products page must still render product overview sections.");
assert.equal(/function applyRevealMotion\(\)[\s\S]*document\.querySelectorAll\([\s\S]*\.product-overview/.test(appSource), false, "Admin product panels must not be hidden behind reveal observer opacity.");
assert.equal(appSource.includes("const activeProductModels = productModels.filter((model) => model.published);"), true, "Admin products page must default to the published source-truth product set.");
assert.equal(appSource.includes("archived products are hidden from this view"), true, "Admin products page must explain that archived products are intentionally hidden.");
assert.equal(appSource.includes("data-action=\"save-product-price\""), true, "Admin products page must let admins save prices on existing products.");
assert.equal(appSource.includes('class="admin-stock-details"'), true, "Admin product size and stock details must be collapsible.");
assert.equal(appSource.includes("const sizes = matrix.sizes.slice(0, 6);"), false, "Admin stock matrix must not hide sizes after the first six.");
assert.equal(appSource.includes(".slice(0, 4)\n          .map(\n            (row) => `\n              <div class=\"stock-matrix-row\">"), false, "Admin stock matrix must not hide colour stock rows after the first four.");
assert.equal(appSource.includes("Showing top stock rows"), false, "Admin stock matrix must not claim it is hiding stock rows.");
assert.equal(appSource.includes("--stock-size-count"), true, "Admin stock matrix must size columns dynamically for all size options.");
assert.equal(appSource.includes("activeProducts\n              .slice(0, 6)"), false, "Admin product overview must not hide active products after the first six.");
assert.equal(appSource.includes("async function updateAuthedSupabase("), true, "Admin price edits must use authenticated Supabase updates.");
assert.equal(appSource.includes("async function handleProductPriceUpdate("), true, "Admin price edits must have a dedicated handler.");
assert.equal(appSource.includes("Reset All Stock"), true, "Admin inventory page must expose a clear stock reset control.");
assert.equal(appSource.includes("Type RESET STOCK to confirm"), true, "Stock reset must require typed confirmation.");
assert.equal(appSource.includes("async function handleStockReset("), true, "Admin stock reset must have a dedicated handler.");
assert.equal(appSource.includes("async function patchAuthedSupabaseMinimal("), true, "Bulk stock reset must use minimal PATCH responses.");
assert.equal(appSource.includes('patchAuthedSupabaseMinimal("inventory", "id=not.is.null"'), true, "Stock reset must zero every inventory row.");
assert.equal(appSource.includes("source: \"manual_stock_reset\""), true, "Stock reset must mark inventory rows with a reset source.");
assert.equal(appSource.includes("async function depleteSubmittedOrderStock("), false, "Order submission must not deplete stock immediately.");
assert.equal(appSource.includes("source: \"order_submitted\""), false, "Submitted orders must not change inventory immediately.");
assert.equal(appSource.includes("AdminOrders.buildApprovalInventoryAdjustments"), true, "Admin approval must allocate stock from the actual request items.");
assert.equal(appSource.includes("source: \"order_approved\""), true, "Approved orders must mark stock rows as order-approved adjustments.");
assert.equal(appSource.includes("Stock updates only after approval."), true, "Reseller messaging must match approval-based stock deduction.");
assert.equal(appSource.includes("Price pending"), true, "Reseller shop must show pending price instead of a false zero price.");
assert.equal(appSource.includes('<div><button disabled>Prev</button><button class="active">1</button><button>2</button><button>3</button><button>Next</button></div>'), false, "Catalog pager must not be static fake controls.");
assert.equal(appSource.includes("data-action=\"catalog-page\""), true, "Catalog pager buttons must have real page actions.");
assert.equal(appSource.includes("data-action=\"select-gallery-image\""), true, "Product detail thumbnails must be wired as selectable gallery buttons.");
assert.equal(appSource.includes("[data-product-detail-main] .product-visual"), true, "Product detail thumbnail clicks must target the main product visual.");
assert.equal(appSource.includes("photo.setAttribute(\"src\", imageUrl);"), true, "Product detail thumbnail clicks must update the main product photo.");
assert.equal(appSource.includes("Colour Review"), true, "Admin products page must include the Colour Review section.");
assert.equal(appSource.includes("product_colour_mappings"), true, "Colour Review must save against product_colour_mappings.");
assert.equal(appSource.includes("original_colour"), true, "Colour Review wiring must preserve original_colour keys.");
assert.equal(indexSource.includes('rel="icon"'), true, "Document head must declare a favicon to avoid localhost favicon 404s.");
assert.equal(indexSource.includes("irunsvan-admin-images-v2"), true, "Index must bump static asset cache keys after the image containment pass.");
assert.equal(appSource.includes("object-fit: contain"), false, "Image sizing changes must live in CSS, not inline styles.");
const oldBrandSlug = "ivan" + "srun";
const oldBrandName = "Ivan" + "srun";
assert.equal(indexSource.includes(`${oldBrandSlug}-google-auth-v1`), false, "Index must not keep the stale Google OAuth cache key after Irunsvan brand correction.");
assert.equal(indexSource.includes(`${oldBrandName} Africa`), false, "Visible document metadata must use Irunsvan Africa branding.");
assert.equal(appSource.includes(`${oldBrandName} Africa`), false, "Frontend copy must use Irunsvan Africa branding.");
assert.equal(appSource.includes(`${oldBrandName} reseller`), false, "Frontend fallback company copy must use Irunsvan reseller branding.");
assert.equal(indexSource.includes(`${oldBrandSlug}-real-auth-v1`), false, "Index must not keep the stale real-auth cache key after Google OAuth login.");
assert.equal(indexSource.includes(`${oldBrandSlug}-stock-reset-v1`), false, "Index must not keep the stale stock reset cache key after Google OAuth login.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v3`), false, "Index must not keep the stale reseller detail cache key after stock reset and depletion fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v2`), false, "Index must not keep the stale reseller detail runtime cache key after layout fix.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-detail-v1`), false, "Index must not keep the stale reseller detail cache key after runtime fix.");
assert.equal(indexSource.includes(`${oldBrandSlug}-bulk-order-v1`), false, "Index must not keep the stale bulk-order cache key after reseller product detail UI fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-auth-stock-v2`), false, "Index must not keep the stale auth stock cache key after bulk-order UI fixes.");
assert.equal(indexSource.includes(`${oldBrandSlug}-ops-repair-v1`), false, "Index must not keep the stale operations cache key after auth and stock visibility fixes.");
assert.equal(indexSource.includes("operations-products.js"), true, "Index must load the operations product view-model helper before app.js.");
assert.equal(indexSource.includes("xlsx.full.min.js"), false, "XLSX import library must be lazy-loaded only when admin imports need it.");
assert.equal(indexSource.includes("jszip.min.js"), false, "JSZip import library must be lazy-loaded only when admin imports need it.");
assert.equal(appSource.includes("async function ensureImportLibraries("), true, "Admin imports must load spreadsheet/archive libraries on demand.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v4`), false, "Index must not keep the stale reseller portal v4 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v3`), false, "Index must not keep the stale reseller portal v3 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-reseller-shop-v2`), false, "Index must not keep the stale reseller portal v2 cache key.");
assert.equal(indexSource.includes(`${oldBrandSlug}-clear-products-v1`), false, "Index must not keep the stale reseller portal cache key.");
assert.equal(staticServerSource.includes("response.on(\"finish\""), true, "Static server must log each response for local request monitoring.");
assert.equal(staticServerSource.includes("console.log(`[static-server]"), true, "Static server logs must emit structured monitoring lines.");
assert.equal(staticServerSource.includes("/__dev/prelogin"), false, "Static server must not expose a dev-only test prelogin endpoint.");
assert.equal(staticServerSource.includes("ENABLE_TEST_LOGIN"), false, "Static server must not contain a test-login feature flag.");
assert.equal(staticServerSource.includes(`${oldBrandSlug}_auth_session`), false, "Static server must not write auth sessions.");
["AdminTest!2026", "OpsAdmin!2026", "ResellerTest!2026", "PendingTest!2026"].forEach((password) => {
  assert.equal(appSource.includes(password), false, `Frontend must not contain committed password ${password}.`);
  assert.equal(staticServerSource.includes(password), false, `Static server must not contain committed password ${password}.`);
  assert.equal(createTestAdminsSource.includes(password), false, `Test account setup must not contain committed password ${password}.`);
});
assert.equal(createTestAdminsSource.includes("passwordEnv"), true, "Test account setup must source passwords from environment variables.");

console.log("app-wiring tests passed");
