const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const pricePrivacySql = readFileSync(join(__dirname, "..", "supabase", "sql", "009_reseller_price_privacy_and_grants.sql"), "utf8");
const catchupSql = readFileSync(join(__dirname, "..", "supabase", "sql", "010_schema_catchup_repair.sql"), "utf8");
const skuFirstSql = readFileSync(join(__dirname, "..", "supabase", "sql", "011_sku_first_catalog_import.sql"), "utf8");
const authorizedPriceSql = readFileSync(join(__dirname, "..", "supabase", "sql", "012_authorized_price_feeds.sql"), "utf8");
const skuSourceTruthSql = readFileSync(join(__dirname, "..", "supabase", "sql", "013_sku_zip_source_truth_images.sql"), "utf8");
const brandCleanupSql = readFileSync(join(__dirname, "..", "supabase", "sql", "014_irunsvan_brand_text_cleanup.sql"), "utf8");
const accountDirectorySql = readFileSync(join(__dirname, "..", "supabase", "sql", "015_account_and_directory.sql"), "utf8");
const adminInvitesSql = readFileSync(join(__dirname, "..", "supabase", "sql", "016_admin_invites.sql"), "utf8");
const publicHomeContentSql = readFileSync(join(__dirname, "..", "supabase", "sql", "018_public_home_content.sql"), "utf8");
const orderWorkflowSql = readFileSync(join(__dirname, "..", "supabase", "sql", "019_order_workflow_statuses.sql"), "utf8");
const publicProductFlyersSql = readFileSync(join(__dirname, "..", "supabase", "sql", "020_public_product_flyers.sql"), "utf8");
const publicProductFlyerImagesSql = readFileSync(join(__dirname, "..", "supabase", "sql", "021_public_product_flyer_images.sql"), "utf8");
const publicProductFlyerImageAdvisorFixesSql = readFileSync(join(__dirname, "..", "supabase", "sql", "022_public_product_flyer_image_advisor_fixes.sql"), "utf8");

assert.match(pricePrivacySql, /create or replace view public\.reseller_products\s+with \(security_invoker = true\)/i);
assert.match(pricePrivacySql, /create or replace view public\.reseller_product_variants\s+with \(security_invoker = true\)/i);
assert.equal(/create or replace view public\.reseller_products[\s\S]*base_price[\s\S]*from public\.products/i.test(pricePrivacySql), false, "Protected product view must not require price columns withheld from base-table grants.");
assert.equal(/create or replace view public\.reseller_product_variants[\s\S]*base_price[\s\S]*from public\.product_variants/i.test(pricePrivacySql), false, "Protected variant view must not require price columns withheld from base-table grants.");
assert.match(pricePrivacySql, /revoke all on public\.products from anon, authenticated;/i);
assert.match(pricePrivacySql, /revoke all on public\.product_variants from anon, authenticated;/i);
assert.equal(/grant select \([^)]*base_price/is.test(pricePrivacySql), false, "Public table grants must not expose base_price columns.");
assert.equal(/grant select \([^)]*base_currency/is.test(pricePrivacySql), false, "Public table grants must not expose base_currency columns.");

assert.match(catchupSql, /create table if not exists public\.hero_sections/i);
assert.match(catchupSql, /create table if not exists public\.site_themes/i);
assert.match(catchupSql, /create table if not exists public\.site_content/i);
assert.match(catchupSql, /alter table public\.products[\s\S]*add column if not exists model_code text/i);
assert.match(catchupSql, /alter table public\.products[\s\S]*add column if not exists product_type text not null default 'shoe'/i);
assert.match(catchupSql, /alter table public\.product_variants[\s\S]*add column if not exists original_colour text/i);
assert.match(catchupSql, /alter table public\.product_variants[\s\S]*add column if not exists color_code text/i);
assert.match(catchupSql, /alter type public\.import_job_type add value if not exists 'catalog_seed_inventory'/i);
assert.match(catchupSql, /alter type public\.import_job_type add value if not exists 'media_pack_zip'/i);
assert.match(catchupSql, /create or replace view public\.reseller_products\s+with \(security_invoker = true\)/i);
assert.match(catchupSql, /create or replace view public\.reseller_product_variants\s+with \(security_invoker = true\)/i);
assert.equal(/create or replace view public\.reseller_products[\s\S]*base_price[\s\S]*from public\.products/i.test(catchupSql), false, "Catch-up product view must not require price columns withheld from base-table grants.");
assert.equal(/create or replace view public\.reseller_product_variants[\s\S]*base_price[\s\S]*from public\.product_variants/i.test(catchupSql), false, "Catch-up variant view must not require price columns withheld from base-table grants.");
assert.match(catchupSql, /update public\.products[\s\S]*set model_code = regexp_replace\(sku, '\^IRUNSVAN-', ''\)/i);
assert.match(catchupSql, /update public\.product_variants[\s\S]*set original_colour = colour/i);
assert.match(catchupSql, /insert into public\.product_colour_mappings/i);
assert.equal(/grant select \([^)]*base_price/is.test(catchupSql), false, "Catch-up public grants must not expose base_price columns.");
assert.equal(/grant select \([^)]*base_currency/is.test(catchupSql), false, "Catch-up public grants must not expose base_currency columns.");

assert.match(skuFirstSql, /create table if not exists public\.product_colour_mappings/i);
assert.match(skuFirstSql, /unique \(product_id, original_colour, color_code\)/i);
assert.match(skuFirstSql, /alter table public\.product_colour_mappings enable row level security/i);
assert.match(skuFirstSql, /grant select on public\.product_colour_mappings to anon, authenticated/i);
assert.match(skuFirstSql, /grant insert, update, delete on public\.product_colour_mappings to authenticated/i);

assert.match(authorizedPriceSql, /create or replace view public\.authorized_product_prices/i);
assert.match(authorizedPriceSql, /create or replace view public\.authorized_variant_prices/i);
assert.match(authorizedPriceSql, /base_price/i);
assert.match(authorizedPriceSql, /private\.is_admin\(\)/i);
assert.match(authorizedPriceSql, /private\.is_approved_reseller\(\)/i);
assert.match(authorizedPriceSql, /revoke all on public\.authorized_product_prices from public, anon, authenticated/i);
assert.match(authorizedPriceSql, /revoke all on public\.authorized_variant_prices from public, anon, authenticated/i);
assert.match(authorizedPriceSql, /grant select on public\.authorized_product_prices to authenticated/i);
assert.match(authorizedPriceSql, /grant select on public\.authorized_variant_prices to authenticated/i);
assert.equal(/grant select \([^)]*base_price/is.test(authorizedPriceSql), false, "Authorized price feeds must not add public base table price grants.");

assert.match(skuSourceTruthSql, /SKU image folders are the product source of truth/i);
assert.match(skuSourceTruthSql, /model_code not in \(select model_code from public\.products/i);
assert.match(skuSourceTruthSql, /published = si\.model_code is not null/i);
assert.match(skuSourceTruthSql, /\/public\/product-images\/SKUs\/087\/1\.jpg/i);
assert.match(skuSourceTruthSql, /\/public\/product-images\/SKUs\/128\/01\.jpg/i);
assert.match(skuSourceTruthSql, /public\.product_variants[\s\S]*published = vm\.model_code in/i);

const oldBrandName = "Ivan" + "srun Africa";
assert.equal(new RegExp(oldBrandName).test(catchupSql), false, "Catch-up schema must seed Irunsvan branding.");
assert.match(brandCleanupSql, /update public\.products[\s\S]*description = replace\(description, concat\('Ivan', 'srun Africa'\), 'Irunsvan Africa'\)/i);
assert.match(brandCleanupSql, /update public\.hero_sections[\s\S]*copy = replace\(copy, concat\('Ivan', 'srun Africa'\), 'Irunsvan Africa'\)/i);
assert.match(brandCleanupSql, /update public\.site_content[\s\S]*reseller_banner = replace\(reseller_banner, concat\('Ivan', 'srun Africa'\), 'Irunsvan Africa'\)/i);
assert.equal(/reseller_company/.test(brandCleanupSql), false, "Brand cleanup must not reference non-schema order request columns.");

assert.match(accountDirectorySql, /create or replace function public\.update_own_profile/i);
assert.match(accountDirectorySql, /where id = \(select auth\.uid\(\)\)/i);
assert.match(accountDirectorySql, /grant execute on function public\.update_own_profile\(text, text, text\) to authenticated/i);
assert.match(accountDirectorySql, /create or replace view public\.reseller_directory/i);
assert.match(accountDirectorySql, /applications\.status = 'approved'::public\.application_status/i);
assert.match(accountDirectorySql, /profiles\.role = 'reseller'::public\.user_role/i);
assert.match(accountDirectorySql, /grant select on public\.reseller_directory to anon, authenticated/i);

assert.match(adminInvitesSql, /create type public\.admin_invite_status as enum \('pending', 'used', 'revoked', 'expired'\)/i);
assert.match(adminInvitesSql, /create table if not exists public\.admin_invites/i);
assert.match(adminInvitesSql, /token_hash text not null unique/i);
assert.match(adminInvitesSql, /extensions\.digest\(lower\(btrim\(coalesce\(p_token, ''\)\)\), 'sha256'\)/i);
assert.match(adminInvitesSql, /grant select, insert, update, delete on public\.admin_invites to authenticated/i);
assert.match(adminInvitesSql, /create policy "admin_invites_admin_all"/i);
assert.match(adminInvitesSql, /create or replace function public\.lookup_admin_invite/i);
assert.match(adminInvitesSql, /create or replace function public\.claim_admin_invite/i);
assert.match(adminInvitesSql, /revoke all on function public\.claim_admin_invite\(text\) from public, anon, authenticated, service_role/i);
assert.match(adminInvitesSql, /grant execute on function public\.lookup_admin_invite\(text\) to anon, authenticated/i);
assert.match(adminInvitesSql, /grant execute on function public\.claim_admin_invite\(text\) to authenticated/i);
assert.match(adminInvitesSql, /notify pgrst, 'reload schema'/i);

assert.match(publicHomeContentSql, /create table if not exists public\.homepage_flyers/i);
assert.match(publicHomeContentSql, /create table if not exists public\.blog_posts/i);
assert.match(publicHomeContentSql, /alter table public\.homepage_flyers enable row level security/i);
assert.match(publicHomeContentSql, /alter table public\.blog_posts enable row level security/i);

assert.match(publicProductFlyersSql, /create table if not exists public\.public_product_flyers/i);
assert.match(publicProductFlyersSql, /slug text not null unique/i);
assert.match(publicProductFlyersSql, /product_class text not null/i);
assert.match(publicProductFlyersSql, /main_image_path text/i);
assert.match(publicProductFlyersSql, /secondary_image_path text/i);
assert.match(publicProductFlyersSql, /create index if not exists public_product_flyers_public_idx/i);
assert.match(publicProductFlyersSql, /alter table public\.public_product_flyers enable row level security/i);
assert.match(publicProductFlyersSql, /grant select on table public\.public_product_flyers to anon, authenticated/i);
assert.match(publicProductFlyersSql, /grant insert, update, delete on table public\.public_product_flyers to authenticated/i);
assert.match(publicProductFlyersSql, /Public can read published product flyers/i);
assert.match(publicProductFlyersSql, /Admins can manage product flyers/i);
assert.match(publicProductFlyersSql, /private\.is_admin\(\)/i);
assert.match(publicProductFlyersSql, /insert into public\.public_product_flyers/i);
assert.match(publicProductFlyersSql, /Everyday Trainer/i);
assert.match(publicProductFlyersSql, /Performance Trainer/i);
assert.match(publicProductFlyersSql, /Race Day Performance/i);
assert.match(publicProductFlyersSql, /irunsvan-2503-shadow-wing-2-0-pro/i);
assert.match(publicProductFlyersSql, /on conflict \(slug\) do update/i);
assert.match(publicProductFlyerImagesSql, /create table if not exists public\.public_product_flyer_images/i);
assert.match(publicProductFlyerImagesSql, /flyer_id uuid not null references public\.public_product_flyers\(id\) on delete cascade/i);
assert.match(publicProductFlyerImagesSql, /image_name text/i);
assert.match(publicProductFlyerImagesSql, /sku_reference text/i);
assert.match(publicProductFlyerImagesSql, /color_name text/i);
assert.match(publicProductFlyerImagesSql, /caption text/i);
assert.match(publicProductFlyerImagesSql, /is_cover boolean not null default false/i);
assert.match(publicProductFlyerImagesSql, /public_product_flyer_images_max_20/i);
assert.match(publicProductFlyerImagesSql, /create index if not exists public_product_flyer_images_order_idx/i);
assert.match(publicProductFlyerImagesSql, /alter table public\.public_product_flyer_images enable row level security/i);
assert.match(publicProductFlyerImagesSql, /grant select on table public\.public_product_flyer_images to anon, authenticated/i);
assert.match(publicProductFlyerImagesSql, /grant insert, update, delete on table public\.public_product_flyer_images to authenticated/i);
assert.match(publicProductFlyerImagesSql, /Public can read published product flyer images/i);
assert.match(publicProductFlyerImagesSql, /Admins can manage product flyer images/i);
assert.match(publicProductFlyerImagesSql, /private\.is_admin\(\)/i);
assert.match(publicProductFlyerImagesSql, /notify pgrst, 'reload schema'/i);
assert.match(publicProductFlyerImageAdvisorFixesSql, /set search_path = ''/i);
assert.match(publicProductFlyerImageAdvisorFixesSql, /public_product_flyer_images_created_by_idx/i);
assert.match(publicProductFlyerImageAdvisorFixesSql, /public_product_flyer_images_updated_by_idx/i);
assert.match(publicProductFlyerImageAdvisorFixesSql, /Authenticated can read product flyer images/i);
assert.match(publicProductFlyerImageAdvisorFixesSql, /Admins can update product flyer images/i);
assert.match(publicHomeContentSql, /using \(published = true\)/i);
assert.match(publicHomeContentSql, /private\.is_admin\(\)/i);
assert.match(publicHomeContentSql, /alter table public\.site_content[\s\S]*add column if not exists about_heading text/i);
assert.match(publicHomeContentSql, /alter table public\.site_content[\s\S]*add column if not exists about_body text/i);
assert.match(publicHomeContentSql, /storage\.buckets[\s\S]*'product-images'/i);
assert.match(publicHomeContentSql, /content\/%/i);

assert.match(orderWorkflowSql, /alter type public\.order_request_status add value if not exists 'awaiting_payment'/i);
assert.match(orderWorkflowSql, /alter type public\.order_request_status add value if not exists 'paid'/i);
assert.match(orderWorkflowSql, /alter type public\.order_request_status add value if not exists 'submitted_to_supplier'/i);
assert.match(orderWorkflowSql, /alter type public\.order_request_status add value if not exists 'processing'/i);
assert.match(orderWorkflowSql, /alter type public\.order_request_status add value if not exists 'shipped'/i);
assert.match(orderWorkflowSql, /alter table public\.order_requests[\s\S]*add column if not exists approved_at timestamptz/i);
assert.match(orderWorkflowSql, /alter table public\.order_requests[\s\S]*add column if not exists expected_fulfillment_date date/i);
assert.match(orderWorkflowSql, /alter table public\.order_requests[\s\S]*add column if not exists processing_at timestamptz/i);
assert.match(orderWorkflowSql, /alter table public\.order_requests[\s\S]*add column if not exists supplier_exported_at timestamptz/i);

console.log("supabase-sql tests passed");
